package com.nttd.banking.customer.domain.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.nttd.banking.customer.domain.model.enums.CustomerStatus;
import com.nttd.banking.customer.domain.model.enums.CustomerType;
import com.nttd.banking.customer.domain.model.enums.DocumentType;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Abstract base domain entity for all customer types.
 *
 * @author NTT Data
 * @version 1.0
 */
@Data
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public abstract class Customer {

  /** Unique customer identifier generated by MongoDB. */
  private String id;

  /** Customer type discriminator (PERSONAL or BUSINESS). */
  private CustomerType customerType;

  /** Identity document type. */
  private DocumentType documentType;

  /** Identity document number (unique). */
  private String documentNumber;

  /** Customer email address (unique). */
  private String email;

  /** Customer phone number. */
  private String phoneNumber;

  /** Customer address. */
  private String address;

  /** Customer status (ACTIVE, INACTIVE, BLOCKED). */
  private CustomerStatus status;

  /** Record creation timestamp. */
  private Instant createdAt;

  /** Record last update timestamp. */
  private Instant updatedAt;

  /**
   * Validates common customer data.
   *
   * @throws IllegalArgumentException if any field is invalid
   */
  public void validate() {
    validateDocumentation();
    validateContactInfo();
  }

  /**
   * Validates documentation data.
   *
   * @throws IllegalArgumentException if documentation is invalid
   */
  private void validateDocumentation() {
    if (documentType == null) {
      throw new IllegalArgumentException("El tipo de documento es obligatorio");
    }
    if (documentNumber == null || documentNumber.trim().isEmpty()) {
      throw new IllegalArgumentException("El número de documento es obligatorio");
    }
    if (documentNumber.length() < 8 || documentNumber.length() > 20) {
      throw new IllegalArgumentException("El número de documento debe tener entre 8 y 20 caracteres");
    }
  }

  /**
   * Validates contact information.
   *
   * @throws IllegalArgumentException if contact info is invalid
   */
  private void validateContactInfo() {
    if (email == null || email.trim().isEmpty()) {
      throw new IllegalArgumentException("El email es obligatorio");
    }
    if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
      throw new IllegalArgumentException("El email no tiene un formato válido");
    }
    if (phoneNumber == null || phoneNumber.trim().isEmpty()) {
      throw new IllegalArgumentException("El número de teléfono es obligatorio");
    }
    if (address == null || address.trim().isEmpty()) {
      throw new IllegalArgumentException("La dirección es obligatoria");
    }
    if (address.length() < 10 || address.length() > 200) {
      throw new IllegalArgumentException("La dirección debe tener entre 10 y 200 caracteres");
    }
  }

  /**
   * Activates the customer by setting status to ACTIVE.
   */
  public void activate() {
    this.status = CustomerStatus.ACTIVE;
    this.updatedAt = Instant.now();
  }

  /**
   * Deactivates the customer by setting status to INACTIVE.
   */
  public void deactivate() {
    this.status = CustomerStatus.INACTIVE;
    this.updatedAt = Instant.now();
  }

  /**
   * Blocks the customer by setting status to BLOCKED.
   */
  public void block() {
    this.status = CustomerStatus.BLOCKED;
    this.updatedAt = Instant.now();
  }

  /**
   * Checks if customer is active.
   *
   * @return true if customer status is ACTIVE
   */
  @JsonIgnore
  public boolean isActive() {
    return CustomerStatus.ACTIVE.equals(this.status);
  }

  /**
   * Checks if customer is blocked.
   *
   * @return true if customer status is BLOCKED
   */
  @JsonIgnore
  public boolean isBlocked() {
    return CustomerStatus.BLOCKED.equals(this.status);
  }

  /**
   * Updates the last modification timestamp.
   */
  public void touch() {
    this.updatedAt = Instant.now();
  }

  /**
   * Initializes default values for a new customer.
   */
  public void initializeDefaults() {
    if (this.status == null) {
      this.status = CustomerStatus.ACTIVE;
    }
    if (this.createdAt == null) {
      this.createdAt = Instant.now();
    }
    if (this.updatedAt == null) {
      this.updatedAt = Instant.now();
    }
  }
}
